import { recompute } from "@/lib/inventory";
import type { Database, Item, Movement, Purchase, Supplier } from "@/lib/types";

function stamp(date: string, seq: number) {
  return `${date}T10:${String(seq).padStart(2, "0")}:00.000Z`;
}

function supplier(
  id: string,
  name: string,
  contact: string,
  phone: string,
  email: string,
  address: string,
  notes: string,
): Supplier {
  return {
    id,
    name,
    contact,
    phone,
    email,
    address,
    notes,
    createdAt: "2026-05-01T08:00:00.000Z",
  };
}

function item(input: {
  id: string;
  sku: string;
  name: string;
  category: string;
  unit: string;
  description: string;
  location: string;
  reorderLevel: number;
  supplierId: string;
}): Item {
  return {
    ...input,
    quantityOnHand: 0,
    averageCost: 0,
    lastPurchasePrice: 0,
    lastPurchaseDate: null,
    createdAt: "2026-05-01T08:00:00.000Z",
    updatedAt: "2026-09-22T12:00:00.000Z",
  };
}

function purchase(
  id: string,
  itemId: string,
  supplierId: string,
  date: string,
  quantity: number,
  unitPrice: number,
  invoiceNo: string,
  notes: string,
  seq: number,
): Purchase {
  return {
    id,
    itemId,
    supplierId,
    date,
    quantity,
    unitPrice,
    invoiceNo,
    notes,
    createdAt: stamp(date, seq),
  };
}

function movement(
  id: string,
  itemId: string,
  date: string,
  direction: "in" | "out",
  quantity: number,
  reason: string,
  reference: string,
  notes: string,
  seq: number,
): Movement {
  return {
    id,
    itemId,
    date,
    direction,
    quantity,
    reason,
    reference,
    notes,
    createdAt: stamp(date, seq),
  };
}

export function createSeed(): Database {
  const db: Database = {
    meta: { usingSample: true, noticeDismissed: false },
    suppliers: [
      supplier(
        "sup-paper",
        "Paper House Karachi",
        "Imran Qureshi",
        "021-111-456-789",
        "orders@paperhouse.example",
        "Shahrah-e-Faisal, Karachi",
        "House papers and boards. Delivers twice a week.",
      ),
      supplier(
        "sup-ink",
        "Gulf Ink Traders",
        "Sana Malik",
        "021-3498-2210",
        "sana@gulflink.example",
        "SITE Area, Karachi",
        "Process inks and overprint varnishes.",
      ),
      supplier(
        "sup-plate",
        "Precision Plates",
        "Adeel Raza",
        "021-3567-9044",
        "adeel@precisionplates.example",
        "Korangi Industrial Area, Karachi",
        "CTP thermal plates, 510×400 mm.",
      ),
      supplier(
        "sup-chem",
        "ChemSol Industries",
        "Hira Noor",
        "021-3501-7781",
        "sales@chemsol.example",
        "Port Qasim, Karachi",
        "Fountain solution, blanket wash, and IPA.",
      ),
      supplier(
        "sup-finish",
        "BindRight Supplies",
        "Farhan Ali",
        "021-111-908-334",
        "hello@bindright.example",
        "Liaquatabad, Karachi",
        "Glue, lamination film, and dispatch cartons.",
      ),
    ],
    items: [
      item({
        id: "item-art-300",
        sku: "PW-001",
        name: "Art Card 300gsm SRA3",
        category: "Paper & Board",
        unit: "Ream",
        description: "Coated art card for covers, folders, and business cards.",
        location: "Rack A1",
        reorderLevel: 20,
        supplierId: "sup-paper",
      }),
      item({
        id: "item-art-350",
        sku: "PW-002",
        name: "Art Card 350gsm SRA3",
        category: "Paper & Board",
        unit: "Ream",
        description: "Heavier art card for packaging sleeves and invitation covers.",
        location: "Rack A1",
        reorderLevel: 12,
        supplierId: "sup-paper",
      }),
      item({
        id: "item-offset-80",
        sku: "PW-003",
        name: "Offset Paper 80gsm 23×36",
        category: "Paper & Board",
        unit: "Ream",
        description: "Book and leaflet text stock. Full-size press sheet.",
        location: "Warehouse",
        reorderLevel: 40,
        supplierId: "sup-paper",
      }),
      item({
        id: "item-offset-128",
        sku: "PW-004",
        name: "Offset Paper 128gsm 23×36",
        category: "Paper & Board",
        unit: "Ream",
        description: "Heavier text and poster stock.",
        location: "Warehouse",
        reorderLevel: 15,
        supplierId: "sup-paper",
      }),
      item({
        id: "item-sticker",
        sku: "PW-005",
        name: "Gloss Sticker Paper A4",
        category: "Paper & Board",
        unit: "Packet",
        description: "Self-adhesive gloss sheets for labels and stickers.",
        location: "Rack A3",
        reorderLevel: 10,
        supplierId: "sup-paper",
      }),
      item({
        id: "item-cyan",
        sku: "PW-006",
        name: "Process Cyan Ink 1kg",
        category: "Ink & Toner",
        unit: "Can",
        description: "Sheetfed process cyan.",
        location: "Ink Store",
        reorderLevel: 8,
        supplierId: "sup-ink",
      }),
      item({
        id: "item-magenta",
        sku: "PW-007",
        name: "Process Magenta Ink 1kg",
        category: "Ink & Toner",
        unit: "Can",
        description: "Sheetfed process magenta. Watch this one — it runs out first.",
        location: "Ink Store",
        reorderLevel: 8,
        supplierId: "sup-ink",
      }),
      item({
        id: "item-yellow",
        sku: "PW-008",
        name: "Process Yellow Ink 1kg",
        category: "Ink & Toner",
        unit: "Can",
        description: "Sheetfed process yellow.",
        location: "Ink Store",
        reorderLevel: 8,
        supplierId: "sup-ink",
      }),
      item({
        id: "item-black",
        sku: "PW-009",
        name: "Process Black Ink 1kg",
        category: "Ink & Toner",
        unit: "Can",
        description: "Sheetfed process black.",
        location: "Ink Store",
        reorderLevel: 10,
        supplierId: "sup-ink",
      }),
      item({
        id: "item-plate",
        sku: "PW-010",
        name: "CTP Thermal Plate 510×400",
        category: "Plates",
        unit: "Sheet",
        description: "Thermal CTP plates for the main press.",
        location: "Plate Rack",
        reorderLevel: 100,
        supplierId: "sup-plate",
      }),
      item({
        id: "item-fountain",
        sku: "PW-011",
        name: "Fountain Solution 5L",
        category: "Press Chemicals",
        unit: "Can",
        description: "Concentrate. Mix to press specification before use.",
        location: "Chemical Cage",
        reorderLevel: 4,
        supplierId: "sup-chem",
      }),
      item({
        id: "item-wash",
        sku: "PW-012",
        name: "Blanket Wash 5L",
        category: "Press Chemicals",
        unit: "Can",
        description: "Blanket and roller wash.",
        location: "Chemical Cage",
        reorderLevel: 3,
        supplierId: "sup-chem",
      }),
      item({
        id: "item-ipa",
        sku: "PW-013",
        name: "Isopropyl Alcohol 20L",
        category: "Press Chemicals",
        unit: "Can",
        description: "IPA for the dampening system.",
        location: "Chemical Cage",
        reorderLevel: 2,
        supplierId: "sup-chem",
      }),
      item({
        id: "item-film",
        sku: "PW-014",
        name: "Lamination Film 12 micron",
        category: "Finishing",
        unit: "Roll",
        description: "Gloss thermal lamination film, 1 metre wide.",
        location: "Finishing Bay",
        reorderLevel: 6,
        supplierId: "sup-finish",
      }),
      item({
        id: "item-glue",
        sku: "PW-015",
        name: "Hotmelt Binding Glue",
        category: "Finishing",
        unit: "Kg",
        description: "Perfect-binding hotmelt, 1 kg blocks.",
        location: "Finishing Bay",
        reorderLevel: 8,
        supplierId: "sup-finish",
      }),
      item({
        id: "item-carton",
        sku: "PW-016",
        name: "Book Carton A4",
        category: "Packaging",
        unit: "Piece",
        description: "Dispatch cartons for A4 books and reams.",
        location: "Dispatch",
        reorderLevel: 50,
        supplierId: "sup-finish",
      }),
      item({
        id: "item-blanket",
        sku: "PW-017",
        name: "Press Blanket 510mm",
        category: "Machine Parts",
        unit: "Piece",
        description: "Spare impression blanket for the main press.",
        location: "Parts Room",
        reorderLevel: 1,
        supplierId: "sup-plate",
      }),
      item({
        id: "item-matrix",
        sku: "PW-018",
        name: "Creasing Matrix 0.5mm",
        category: "Finishing",
        unit: "Meter",
        description: "Creasing channel for 300–350gsm covers.",
        location: "Finishing Bay",
        reorderLevel: 20,
        supplierId: "sup-finish",
      }),
    ],
    purchases: [
      purchase("pur-001", "item-art-300", "sup-paper", "2026-07-02", 40, 3900, "INV-2401", "Cover stock for Q3 jobs.", 1),
      purchase("pur-002", "item-art-300", "sup-paper", "2026-08-18", 30, 4150, "INV-2518", "Price revised on this receipt.", 2),
      purchase("pur-003", "item-art-350", "sup-paper", "2026-07-15", 20, 4800, "INV-2420", "", 1),
      purchase("pur-004", "item-offset-80", "sup-paper", "2026-06-28", 80, 2100, "INV-2388", "Bulk text paper.", 1),
      purchase("pur-005", "item-offset-80", "sup-paper", "2026-09-04", 50, 2250, "INV-2604", "", 2),
      purchase("pur-006", "item-offset-128", "sup-paper", "2026-08-02", 25, 3200, "INV-2488", "", 1),
      purchase("pur-007", "item-sticker", "sup-paper", "2026-09-01", 30, 850, "INV-2590", "", 1),
      purchase("pur-008", "item-cyan", "sup-ink", "2026-07-08", 12, 1450, "GI-882", "CMYK replenishment.", 1),
      purchase("pur-009", "item-cyan", "sup-ink", "2026-09-06", 10, 1520, "GI-940", "", 2),
      purchase("pur-010", "item-magenta", "sup-ink", "2026-07-08", 12, 1450, "GI-882", "Same receipt as the other process colours.", 1),
      purchase("pur-011", "item-yellow", "sup-ink", "2026-07-08", 12, 1400, "GI-882", "", 1),
      purchase("pur-012", "item-yellow", "sup-ink", "2026-09-06", 6, 1480, "GI-940", "", 2),
      purchase("pur-013", "item-black", "sup-ink", "2026-07-08", 20, 1250, "GI-882", "", 1),
      purchase("pur-014", "item-black", "sup-ink", "2026-08-25", 10, 1300, "GI-921", "", 2),
      purchase("pur-015", "item-plate", "sup-plate", "2026-08-10", 200, 85, "PP-331", "Quarterly plate order.", 1),
      purchase("pur-016", "item-plate", "sup-plate", "2026-09-11", 100, 88, "PP-358", "", 2),
      purchase("pur-017", "item-fountain", "sup-chem", "2026-07-20", 8, 3200, "CS-110", "", 1),
      purchase("pur-018", "item-wash", "sup-chem", "2026-08-05", 6, 2800, "CS-128", "", 1),
      purchase("pur-019", "item-ipa", "sup-chem", "2026-06-15", 3, 9500, "CS-090", "", 1),
      purchase("pur-020", "item-film", "sup-finish", "2026-08-12", 10, 5400, "BR-77", "", 1),
      purchase("pur-021", "item-glue", "sup-finish", "2026-07-28", 15, 720, "BR-61", "", 1),
      purchase("pur-022", "item-carton", "sup-finish", "2026-09-02", 200, 45, "BR-90", "Dispatch cartons for the book run.", 1),
      purchase("pur-023", "item-blanket", "sup-plate", "2026-05-20", 2, 18500, "PP-290", "Spare blankets kept in the parts room.", 1),
      purchase("pur-024", "item-matrix", "sup-finish", "2026-08-28", 40, 95, "BR-84", "", 1),
    ],
    movements: [
      movement("mov-001", "item-art-300", "2026-08-05", "out", 14, "Production", "PW-118", "Folder job.", 3),
      movement("mov-002", "item-art-300", "2026-09-02", "out", 10, "Production", "PW-140", "Invitation covers.", 4),
      movement("mov-003", "item-art-300", "2026-09-12", "in", 2, "Return to stock", "PW-140", "Over-issue returned from bindery.", 5),
      movement("mov-004", "item-art-300", "2026-09-16", "out", 8, "Production", "PW-155", "", 6),
      movement("mov-005", "item-art-350", "2026-08-20", "out", 6, "Production", "PW-132", "", 2),
      movement("mov-006", "item-art-350", "2026-09-10", "out", 4, "Production", "PW-148", "", 3),
      movement("mov-007", "item-offset-80", "2026-07-20", "out", 30, "Production", "PW-104", "Annual report text.", 3),
      movement("mov-008", "item-offset-80", "2026-08-12", "out", 25, "Production", "PW-126", "", 4),
      movement("mov-009", "item-offset-80", "2026-09-08", "out", 20, "Production", "PW-146", "", 5),
      movement("mov-010", "item-offset-80", "2026-09-20", "out", 18, "Production", "PW-162", "", 6),
      movement("mov-011", "item-offset-128", "2026-08-22", "out", 8, "Production", "PW-134", "", 2),
      movement("mov-012", "item-offset-128", "2026-09-12", "out", 5, "Production", "PW-151", "", 3),
      movement("mov-013", "item-sticker", "2026-09-14", "out", 4, "Production", "PW-153", "Product labels.", 2),
      movement("mov-014", "item-cyan", "2026-08-01", "out", 4, "Production", "PW-121", "", 3),
      movement("mov-015", "item-cyan", "2026-08-28", "out", 3, "Production", "PW-138", "", 4),
      movement("mov-016", "item-cyan", "2026-09-18", "out", 5, "Production", "PW-158", "", 5),
      movement("mov-017", "item-magenta", "2026-08-01", "out", 4, "Production", "PW-121", "", 2),
      movement("mov-018", "item-magenta", "2026-08-28", "out", 4, "Production", "PW-138", "", 3),
      movement("mov-019", "item-magenta", "2026-09-18", "out", 3, "Production", "PW-158", "Almost finished this can set.", 4),
      movement("mov-020", "item-yellow", "2026-08-02", "out", 3, "Production", "PW-121", "", 3),
      movement("mov-021", "item-yellow", "2026-09-09", "out", 4, "Production", "PW-147", "", 4),
      movement("mov-022", "item-black", "2026-07-30", "out", 6, "Production", "PW-116", "", 3),
      movement("mov-023", "item-black", "2026-09-01", "out", 5, "Production", "PW-142", "", 4),
      movement("mov-024", "item-black", "2026-09-19", "out", 5, "Production", "PW-160", "", 5),
      movement("mov-025", "item-plate", "2026-08-30", "out", 80, "Production", "PW-139", "", 3),
      movement("mov-026", "item-plate", "2026-09-15", "out", 90, "Production", "PW-154", "", 4),
      movement("mov-027", "item-plate", "2026-09-21", "out", 8, "Wastage", "PW-170", "Plate jam on the imagesetter.", 5),
      movement("mov-028", "item-plate", "2026-09-22", "out", 62, "Production", "PW-171", "", 6),
      movement("mov-029", "item-fountain", "2026-08-15", "out", 2, "Production", "Press room", "", 2),
      movement("mov-030", "item-fountain", "2026-09-07", "out", 2, "Production", "Press room", "", 3),
      movement("mov-031", "item-wash", "2026-09-03", "out", 1, "Production", "Press room", "Blanket change.", 2),
      movement("mov-032", "item-ipa", "2026-08-08", "out", 1, "Production", "Press room", "", 2),
      movement("mov-033", "item-ipa", "2026-09-19", "out", 2, "Production", "Press room", "", 3),
      movement("mov-034", "item-film", "2026-09-05", "out", 3, "Production", "PW-144", "Cover lamination.", 2),
      movement("mov-035", "item-glue", "2026-08-18", "out", 6, "Production", "PW-130", "Perfect binding.", 2),
      movement("mov-036", "item-glue", "2026-09-09", "out", 5, "Production", "PW-149", "", 3),
      movement("mov-037", "item-glue", "2026-09-21", "out", 4, "Production", "PW-168", "", 4),
      movement("mov-038", "item-carton", "2026-09-17", "out", 40, "Production", "Dispatch", "Book delivery.", 2),
      movement("mov-039", "item-matrix", "2026-09-13", "out", 12, "Production", "PW-152", "", 2),
    ],
  };

  const error = recompute(db);
  if (error) throw new Error(error);
  return db;
}

export function emptyDatabase(): Database {
  return {
    meta: { usingSample: false, noticeDismissed: true },
    items: [],
    suppliers: [],
    purchases: [],
    movements: [],
  };
}
